typeset -U path cdpath fpath manpath
for profile in ${(z)NIX_PROFILES}; do
  fpath+=($profile/share/zsh/site-functions $profile/share/zsh/$ZSH_VERSION/functions $profile/share/zsh/vendor-completions)
done

HELPDIR="/nix/store/gm8ldbac46x710xlmxanblzvw4yimjzd-zsh-5.9/share/zsh/$ZSH_VERSION/help"

# oh-my-zsh extra settings for plugins

# oh-my-zsh configuration generated by NixOS
plugins=(git direnv)


source $ZSH/oh-my-zsh.sh

# History options should be set in .zshrc and after oh-my-zsh sourcing.
# See https://github.com/nix-community/home-manager/issues/177.
HISTSIZE="10000"
SAVEHIST="10000"

HISTFILE="/home/balraj/.zsh_history"
mkdir -p "$(dirname "$HISTFILE")"

setopt HIST_FCNTL_LOCK

# Enabled history options
enabled_opts=(
  HIST_IGNORE_DUPS HIST_IGNORE_SPACE SHARE_HISTORY
)
for opt in "${enabled_opts[@]}"; do
  setopt "$opt"
done
unset opt enabled_opts

# Disabled history options
disabled_opts=(
  APPEND_HISTORY EXTENDED_HISTORY HIST_EXPIRE_DUPS_FIRST HIST_FIND_NO_DUPS
  HIST_IGNORE_ALL_DUPS HIST_SAVE_NO_DUPS
)
for opt in "${disabled_opts[@]}"; do
  unsetopt "$opt"
done
unset opt disabled_opts

      # Set up the prompt
      precmd() {
        RPROMPT="$(__lang_hint)"
      }

      PROMPT='╭─ %F{cyan}%1~%f at %F{yellow}%m%f %F{green}$(git_prompt_info)%f%f
╰─ > '

      __lang_hint() {
        setopt local_options nonomatch
        local icons=""
        local dir="$PWD"

        local reset='%{$reset_color%}'
        local green='%{$fg[green]%}'
        local cyan='%{$fg[cyan]%}'
        local yellow='%{$fg[yellow]%}'
        local red='%{$fg[red]%}'
        local blue='%{$fg[blue]%}'
        local magenta='%{$fg[magenta]%}'
        local white='%{$fg[white]%}'

        [[ -n "$IN_NIX_SHELL" ]] && icons+="[${green}devShell${reset}]"
        [[ -f pyproject.toml ]] && icons+="[${yellow}Python${reset}]"
        [[ -f package.json ]] && icons+="[${reset}Unknown${reset}]"
        [[ -f Cargo.toml ]] && icons+="[${red}Rust${reset}]"
        [[ -f go.mod ]] && icons+="[${blue}Go${reset}]"
        [[ -f flake.nix ]] && icons+="[${cyan}Nix${reset}]"
        [[ -f Makefile ]] && icons+="[${white}C/C++${reset}]"

        for f in "$dir"/*.py; do
          [[ -f "$f" ]] && { icons+="[${yellow}Python${reset}]"; break; }
        done
        for f in "$dir"/*.c "$dir"/*.cpp "$dir"/*.h; do
          [[ -f "$f" ]] && { icons+="[${white}C/C++${reset}]"; break; }
        done
        for f in "$dir"/*.java "$dir"/*.class; do
          [[ -f "$f" ]] && { icons+="[${magenta}Java${reset}]"; break; }
        done
        for f in "$dir"/*.rs; do
          [[ -f "$f" ]] && { icons+="[${red}Rust${reset}]"; break; }
        done
        for f in "$dir"/*.go; do
          [[ -f "$f" ]] && { icons+="[${blue}Go${reset}]"; break; }
        done

        echo -e "$icons"
      }

      export MANPAGER="nvim +Man!"
      export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow'
      eval "$(zoxide init zsh)"
      nitch

alias -- btw='echo I use NixOS, btw'
alias -- cd=z
alias -- edit-config='nvim ~/nixos-dotfiles/configuration.nix'
alias -- edit-home-config='nvim ~/nixos-dotfiles/home.nix'
alias -- ls='eza --long -ahF --no-user --no-permissions --git --icons=always --color=always --grid'
alias -- make-cpp-devshell='bash /home/balraj/nixos-dotfiles/bin/make-cpp-devshell'
alias -- make-py-devshell='bash /home/balraj/nixos-dotfiles/bin/make-py-devshell'
alias -- nc='nvim ~/nixos-dotfiles/.'
alias -- nrs='sudo nixos-rebuild switch --flake ~/nixos-dotfiles/#nixos-btw'